import {
  Activity,
  Banknote,
  BarChart3,
  Bell,
  BookOpen,
  Bot,
  Boxes,
  Building2,
  ChefHat,
  ClipboardList,
  CreditCard,
  Globe2,
  KeyRound,
  LayoutDashboard,
  LayoutGrid,
  Map,
  Package,
  PanelLeft,
  Plug,
  PlusCircle,
  ReceiptText,
  RefreshCw,
  ScrollText,
  Settings,
  Shield,
  ShoppingCart,
  Store,
  Tags,
  Ticket,
  Trash2,
  Truck,
  Users,
  UtensilsCrossed,
} from 'lucide-react';
import type React from 'react';
import { PERMISSIONS, type PermissionId } from '@/constants/permissions';
import type { PlanModuleId } from '@/lib/planLimits';
import type { FeatureFlagKey } from '@/lib/featureFlags';

export type NavLeaf = {
  name: string;
  href: string;
  icon: React.ComponentType<{ className?: string }>;
  end?: boolean;
  requiredPermission?: PermissionId;
  requiredPlanModule?: PlanModuleId;
  /** Progressive plan UI — preferred over plan module alone */
  featureFlag?: FeatureFlagKey;
  superAdminOnly?: boolean;
};

export type NavGroup = {
  id: string;
  label: string;
  /** Hide entire group on Lite for a simpler sidebar */
  hideOnLite?: boolean;
  items: NavLeaf[];
};

export const NAV_GROUPS: NavGroup[] = [
  {
    id: 'service',
    label: 'Front of house',
    items: [
      {
        name: 'Dashboard',
        href: '/erp',
        icon: LayoutDashboard,
        end: true,
        requiredPermission: PERMISSIONS.DASHBOARD_ACCESS,
        featureFlag: 'dashboard',
      },
      {
        name: 'POS (Billing)',
        href: '/erp/pos',
        icon: ShoppingCart,
        requiredPermission: PERMISSIONS.POS_ACCESS,
        requiredPlanModule: 'pos',
        featureFlag: 'pos',
      },
      {
        name: 'Sync Center',
        href: '/erp/sync-center',
        icon: RefreshCw,
        requiredPermission: PERMISSIONS.POS_ACCESS,
        requiredPlanModule: 'pos',
        featureFlag: 'offlineSync',
      },
      {
        name: 'Online Orders',
        href: '/erp/online-orders',
        icon: Globe2,
        requiredPermission: PERMISSIONS.POS_ACCESS,
        requiredPlanModule: 'pos',
        featureFlag: 'onlineOrders',
      },
      {
        name: 'Tables',
        href: '/erp/tables',
        icon: LayoutGrid,
        end: true,
        requiredPermission: PERMISSIONS.TABLES_MANAGE,
        requiredPlanModule: 'tables',
        featureFlag: 'tables',
      },
      {
        name: 'Floor Designer',
        href: '/erp/floor',
        icon: Map,
        requiredPermission: PERMISSIONS.FLOOR_MANAGE,
        requiredPlanModule: 'floorDesigner',
        featureFlag: 'floorDesigner',
      },
      {
        name: 'Kitchen (KDS)',
        href: '/erp/kitchen',
        icon: ChefHat,
        end: true,
        requiredPermission: PERMISSIONS.KITCHEN_ACCESS,
        requiredPlanModule: 'kitchen',
        featureFlag: 'kitchen',
      },
      {
        name: 'Shift / Cash',
        href: '/erp/shifts',
        icon: Banknote,
        requiredPermission: PERMISSIONS.POS_SHIFT,
        requiredPlanModule: 'pos',
        featureFlag: 'shiftManagement',
      },
      {
        name: 'Refunds',
        href: '/erp/refunds',
        icon: ReceiptText,
        requiredPermission: PERMISSIONS.POS_REFUND,
        requiredPlanModule: 'pos',
        featureFlag: 'refundManagement',
      },
      {
        name: 'Audit log',
        href: '/erp/audit',
        icon: ScrollText,
        requiredPermission: PERMISSIONS.POS_AUDIT,
        requiredPlanModule: 'pos',
        featureFlag: 'auditLogs',
      },
    ],
  },
  {
    id: 'menu',
    label: 'Menu & catalog',
    items: [
      {
        name: 'Products',
        href: '/erp/menu/products',
        icon: UtensilsCrossed,
        requiredPermission: PERMISSIONS.MENU_PRODUCTS_MANAGE,
        requiredPlanModule: 'products',
        featureFlag: 'products',
      },
      {
        name: 'Categories',
        href: '/erp/menu/categories',
        icon: Tags,
        requiredPermission: PERMISSIONS.MENU_CATEGORIES_MANAGE,
        requiredPlanModule: 'products',
        featureFlag: 'products',
      },
      {
        name: 'Recipes',
        href: '/erp/menu/recipes',
        icon: BookOpen,
        requiredPermission: PERMISSIONS.RECIPES_MANAGE,
        requiredPlanModule: 'recipes',
        featureFlag: 'recipes',
      },
    ],
  },
  {
    id: 'stock',
    label: 'Inventory & purchase',
    items: [
      {
        name: 'Stock on hand',
        href: '/erp/inventory',
        icon: Boxes,
        end: true,
        requiredPermission: PERMISSIONS.INVENTORY_VIEW,
        requiredPlanModule: 'inventory',
        featureFlag: 'inventory',
      },
      {
        name: 'Daily stock update',
        href: '/erp/inventory/daily',
        icon: ClipboardList,
        requiredPermission: PERMISSIONS.INVENTORY_DAILY,
        requiredPlanModule: 'inventory',
        featureFlag: 'advancedInventory',
      },
      {
        name: 'Adjustments',
        href: '/erp/inventory/adjustments',
        icon: Package,
        requiredPermission: PERMISSIONS.INVENTORY_ADJUST,
        requiredPlanModule: 'inventory',
        featureFlag: 'advancedInventory',
      },
      {
        name: 'Waste log',
        href: '/erp/inventory/waste',
        icon: Trash2,
        requiredPermission: PERMISSIONS.INVENTORY_WASTE,
        requiredPlanModule: 'inventory',
        featureFlag: 'advancedInventory',
      },
      {
        name: 'Purchase orders',
        href: '/erp/purchase',
        icon: Truck,
        end: true,
        requiredPermission: PERMISSIONS.PURCHASE_MANAGE,
        requiredPlanModule: 'purchase',
        featureFlag: 'purchase',
      },
      {
        name: 'Suppliers',
        href: '/erp/purchase/suppliers',
        icon: Store,
        requiredPermission: PERMISSIONS.SUPPLIERS_MANAGE,
        requiredPlanModule: 'suppliers',
        featureFlag: 'suppliers',
      },
    ],
  },
  {
    id: 'growth',
    label: 'Customers & offers',
    hideOnLite: true,
    items: [
      {
        name: 'CRM / Guests',
        href: '/erp/crm',
        icon: Users,
        requiredPermission: PERMISSIONS.CRM_MANAGE,
        requiredPlanModule: 'crm',
        featureFlag: 'customers',
      },
      {
        name: 'Offers & vouchers',
        href: '/erp/vouchers',
        icon: Ticket,
        requiredPermission: PERMISSIONS.MARKETING_MANAGE,
        requiredPlanModule: 'crm',
        featureFlag: 'vouchers',
      },
    ],
  },
  {
    id: 'business',
    label: 'Business',
    items: [
      {
        name: 'Reports',
        href: '/erp/reports',
        icon: BarChart3,
        requiredPermission: PERMISSIONS.REPORTS_VIEW,
        requiredPlanModule: 'reports',
        featureFlag: 'reports',
      },
      {
        name: 'Executive BI',
        href: '/erp/intelligence',
        icon: Activity,
        requiredPermission: PERMISSIONS.SAAS_BI,
        requiredPlanModule: 'aiReports',
        featureFlag: 'executiveBI',
      },
      {
        name: 'AI Copilot',
        href: '/erp/copilot',
        icon: Bot,
        requiredPermission: PERMISSIONS.SAAS_AI,
        requiredPlanModule: 'aiCoach',
        featureFlag: 'aiCopilot',
      },
      {
        name: 'Outlets / Branches',
        href: '/erp/franchise',
        icon: Building2,
        requiredPermission: PERMISSIONS.FRANCHISE_MANAGE,
        requiredPlanModule: 'franchise',
        featureFlag: 'franchise',
      },
      {
        name: 'Platform ops',
        href: '/erp/platform',
        icon: Boxes,
        requiredPermission: PERMISSIONS.SAAS_PLATFORM,
        requiredPlanModule: 'centralInventory',
        featureFlag: 'platformOps',
      },
    ],
  },
  {
    id: 'super-admin',
    label: 'Super Admin',
    items: [
      {
        name: 'Dashboard',
        href: '/erp/super-admin',
        icon: LayoutDashboard,
        requiredPermission: PERMISSIONS.COMPANIES_MANAGE,
        superAdminOnly: true,
        end: true,
      },
      {
        name: 'Companies',
        href: '/erp/super-admin/companies',
        icon: Building2,
        requiredPermission: PERMISSIONS.COMPANIES_MANAGE,
        superAdminOnly: true,
      },
      {
        name: 'Create Company',
        href: '/erp/super-admin/create-company',
        icon: PlusCircle,
        requiredPermission: PERMISSIONS.COMPANIES_MANAGE,
        superAdminOnly: true,
      },
      {
        name: 'Trial Requests',
        href: '/erp/super-admin/trials',
        icon: Ticket,
        requiredPermission: PERMISSIONS.COMPANIES_MANAGE,
        superAdminOnly: true,
      },
      {
        name: 'Subscription Plans',
        href: '/erp/super-admin/plans',
        icon: CreditCard,
        requiredPermission: PERMISSIONS.COMPANIES_MANAGE,
        superAdminOnly: true,
      },
      {
        name: 'Integrations',
        href: '/erp/super-admin/integrations',
        icon: Plug,
        requiredPermission: PERMISSIONS.COMPANIES_MANAGE,
        superAdminOnly: true,
      },
      {
        name: 'Billing',
        href: '/erp/super-admin/billing',
        icon: Banknote,
        requiredPermission: PERMISSIONS.COMPANIES_MANAGE,
        superAdminOnly: true,
      },
      {
        name: 'Notifications',
        href: '/erp/super-admin/notifications',
        icon: Bell,
        requiredPermission: PERMISSIONS.COMPANIES_MANAGE,
        superAdminOnly: true,
      },
      {
        name: 'Settings',
        href: '/erp/super-admin/settings',
        icon: Settings,
        requiredPermission: PERMISSIONS.COMPANIES_MANAGE,
        superAdminOnly: true,
      },
    ],
  },
  {
    id: 'admin',
    label: 'Admin',
    items: [
      {
        name: 'Control Panel',
        href: '/erp/control-panel',
        icon: PanelLeft,
        requiredPermission: PERMISSIONS.SETTINGS_MANAGE,
        requiredPlanModule: 'settings',
        featureFlag: 'controlPanel',
      },
      {
        name: 'Staff & users',
        href: '/erp/users',
        icon: Shield,
        requiredPermission: PERMISSIONS.USERS_MANAGE,
        requiredPlanModule: 'staff',
        featureFlag: 'staff',
      },
      {
        name: 'Login logs',
        href: '/erp/users/logs',
        icon: ClipboardList,
        requiredPermission: PERMISSIONS.USERS_LOGS,
        requiredPlanModule: 'staff',
        featureFlag: 'advancedSecurity',
      },
      {
        name: 'API Platform',
        href: '/erp/api-platform',
        icon: KeyRound,
        requiredPermission: PERMISSIONS.SAAS_API,
        requiredPlanModule: 'api',
        featureFlag: 'apiPlatform',
      },
      {
        name: 'Companies (legacy)',
        href: '/erp/companies',
        icon: Building2,
        requiredPermission: PERMISSIONS.COMPANIES_MANAGE,
        superAdminOnly: true,
      },
      {
        name: 'Settings',
        href: '/erp/settings',
        icon: Settings,
        requiredPermission: PERMISSIONS.SETTINGS_MANAGE,
        requiredPlanModule: 'settings',
        featureFlag: 'settings',
      },
    ],
  },
];
