import {
  Activity,
  Bell,
  Bot,
  Boxes,
  Building2,
  Code2,
  CreditCard,
  Globe2,
  HardDrive,
  Paintbrush,
  Scale,
  Settings2,
  ShoppingBag,
  Store,
  Users,
} from 'lucide-react';
import { PERMISSIONS } from '@/constants/permissions';
import type { ControlModule, QuickAction } from './types';

export const CONTROL_MODULES: ControlModule[] = [
  {
    id: 'business',
    title: 'Business',
    description: 'Profile, GST, taxes, currency, hours, subscription and license.',
    icon: Building2,
    href: '/erp/settings',
    quickActionLabel: 'Open settings',
    status: 'live',
    requiredPermission: PERMISSIONS.SETTINGS_MANAGE,
    requiredPlanModule: 'settings',
    topics: [
      { id: 'profile', label: 'Business Profile', keywords: ['business', 'profile', 'company'], href: '/erp/settings' },
      { id: 'details', label: 'Restaurant Details', keywords: ['restaurant', 'cafe', 'address', 'phone'], href: '/erp/settings' },
      { id: 'hours', label: 'Business Hours', keywords: ['hours', 'open', 'close'], status: 'planned' },
      { id: 'gst', label: 'GST', keywords: ['gst', 'tax', 'gstin'], href: '/erp/settings' },
      { id: 'taxes', label: 'Taxes', keywords: ['tax', 'vat', 'gst'], href: '/erp/settings' },
      { id: 'currency', label: 'Currency', keywords: ['currency', 'inr', 'rupee'], status: 'partial' },
      { id: 'timezone', label: 'Timezone', keywords: ['timezone', 'ist'], status: 'planned' },
      { id: 'service', label: 'Service Charges', keywords: ['service charge', 'sc'], href: '/erp/settings' },
      { id: 'subscription', label: 'Subscription', keywords: ['plan', 'subscription', 'license'], href: '/erp/settings' },
      { id: 'license', label: 'License', keywords: ['license', 'seat'], href: '/erp/settings' },
    ],
  },
  {
    id: 'outlets',
    title: 'Outlets',
    description: 'Branches, franchise, hours, performance and inter-outlet transfer.',
    icon: Store,
    href: '/erp/franchise',
    quickActionLabel: 'Manage outlets',
    status: 'live',
    requiredPermission: PERMISSIONS.FRANCHISE_MANAGE,
    requiredPlanModule: 'franchise',
    topics: [
      { id: 'mgmt', label: 'Outlet Management', keywords: ['outlet', 'branch'], href: '/erp/franchise' },
      { id: 'branches', label: 'Branches', keywords: ['branch', 'location'], href: '/erp/franchise' },
      { id: 'franchise', label: 'Franchise', keywords: ['franchise'], href: '/erp/franchise' },
      { id: 'hours', label: 'Opening Hours', keywords: ['hours'], status: 'planned' },
      { id: 'branch-settings', label: 'Branch Settings', keywords: ['branch settings'], href: '/erp/franchise' },
      { id: 'perf', label: 'Branch Performance', keywords: ['performance', 'kpi'], href: '/erp/intelligence' },
      { id: 'transfer', label: 'Inter Outlet Transfer', keywords: ['transfer', 'stock transfer'], href: '/erp/platform' },
    ],
  },
  {
    id: 'users',
    title: 'Users & Security',
    description: 'Users, roles, permissions, manager PIN, sessions and login history.',
    icon: Users,
    href: '/erp/users',
    quickActionLabel: 'Invite / manage users',
    status: 'live',
    requiredPermission: PERMISSIONS.USERS_MANAGE,
    requiredPlanModule: 'staff',
    topics: [
      { id: 'users', label: 'Users', keywords: ['user', 'staff', 'employee'], href: '/erp/users' },
      { id: 'roles', label: 'Roles', keywords: ['role', 'admin', 'cashier'], href: '/erp/settings?tab=permissions' },
      { id: 'permissions', label: 'Permissions', keywords: ['permission', 'access'], href: '/erp/settings?tab=permissions' },
      { id: 'pin', label: 'Manager PIN', keywords: ['pin', 'manager', 'approval'], href: '/erp/settings?tab=permissions' },
      { id: 'sessions', label: 'Device Sessions', keywords: ['session', 'device'], status: 'planned' },
      { id: 'security', label: 'Security', keywords: ['security', '2fa'], href: '/erp/users' },
      { id: 'login', label: 'Login History', keywords: ['login', 'history', 'logs'], href: '/erp/users/logs' },
      { id: 'password', label: 'Password Policy', keywords: ['password', 'policy'], status: 'planned' },
      { id: '2fa', label: 'Two Factor Authentication', keywords: ['2fa', 'mfa', 'otp'], status: 'planned' },
    ],
  },
  {
    id: 'pos',
    title: 'POS Settings',
    description: 'Receipts, order numbers, kitchen routing, tables, QR and cash drawer.',
    icon: ShoppingBag,
    href: '/erp/settings',
    quickActionLabel: 'Configure POS',
    status: 'partial',
    requiredPermission: PERMISSIONS.SETTINGS_MANAGE,
    requiredPlanModule: 'settings',
    topics: [
      { id: 'config', label: 'POS Configuration', keywords: ['pos', 'billing'], href: '/erp/pos' },
      { id: 'receipt', label: 'Receipt Settings', keywords: ['receipt', 'printer', 'thermal'], href: '/erp/settings' },
      { id: 'orderno', label: 'Order Number', keywords: ['order number', 'sequence'], status: 'planned' },
      { id: 'kitchen', label: 'Kitchen Routing', keywords: ['kitchen', 'kds', 'routing'], href: '/erp/kitchen' },
      { id: 'tables', label: 'Table Configuration', keywords: ['table', 'floor'], href: '/erp/tables' },
      { id: 'qr', label: 'QR Settings', keywords: ['qr', 'menu'], href: '/erp/tables' },
      { id: 'discount', label: 'Discount Rules', keywords: ['discount', 'pin'], href: '/erp/settings?tab=permissions' },
      { id: 'offline', label: 'Offline Mode', keywords: ['offline'], status: 'planned' },
      { id: 'drawer', label: 'Cash Drawer', keywords: ['cash drawer', 'till'], href: '/erp/shifts' },
    ],
  },
  {
    id: 'payments',
    title: 'Payments',
    description: 'Gateways, wallet, gift card, refund and split payment rules.',
    icon: CreditCard,
    href: '/erp/settings?tab=payments',
    quickActionLabel: 'Payment gateways',
    status: 'partial',
    requiredPermission: PERMISSIONS.SETTINGS_MANAGE,
    requiredPlanModule: 'settings',
    topics: [
      { id: 'methods', label: 'Payment Methods', keywords: ['payment', 'cash', 'upi', 'card'], href: '/erp/settings?tab=payments' },
      { id: 'phonepe', label: 'PhonePe', keywords: ['phonepe'], href: '/erp/settings?tab=payments' },
      { id: 'paytm', label: 'Paytm', keywords: ['paytm'], href: '/erp/settings?tab=payments' },
      { id: 'cashfree', label: 'Cashfree', keywords: ['cashfree'], status: 'planned' },
      { id: 'razorpay', label: 'Razorpay', keywords: ['razorpay'], status: 'planned' },
      { id: 'stripe', label: 'Stripe', keywords: ['stripe'], status: 'planned' },
      { id: 'wallet', label: 'Wallet', keywords: ['wallet'], status: 'planned' },
      { id: 'gift', label: 'Gift Card', keywords: ['gift', 'voucher'], href: '/erp/vouchers' },
      { id: 'credit', label: 'Store Credit', keywords: ['store credit'], status: 'planned' },
      { id: 'refund', label: 'Refund Rules', keywords: ['refund'], href: '/erp/refunds' },
      { id: 'split', label: 'Split Payment', keywords: ['split'], href: '/erp/pos/checkout?split=1' },
    ],
  },
  {
    id: 'inventory',
    title: 'Inventory',
    description: 'Stock, recipes, warehouse, alerts, valuation and purchase rules.',
    icon: Boxes,
    href: '/erp/inventory',
    quickActionLabel: 'Stock on hand',
    status: 'live',
    requiredPermission: PERMISSIONS.INVENTORY_VIEW,
    requiredPlanModule: 'inventory',
    topics: [
      { id: 'stock', label: 'Stock Settings', keywords: ['stock', 'inventory'], href: '/erp/inventory' },
      { id: 'recipe', label: 'Recipe Settings', keywords: ['recipe', 'bom'], href: '/erp/menu/recipes' },
      { id: 'warehouse', label: 'Warehouse', keywords: ['warehouse'], status: 'partial' },
      { id: 'batch', label: 'Batch', keywords: ['batch', 'lot'], status: 'planned' },
      { id: 'expiry', label: 'Expiry', keywords: ['expiry', 'fefo'], status: 'planned' },
      { id: 'alerts', label: 'Stock Alerts', keywords: ['low stock', 'alert'], href: '/erp/inventory' },
      { id: 'valuation', label: 'Inventory Valuation', keywords: ['valuation', 'cogs'], status: 'planned' },
      { id: 'purchase', label: 'Purchase Rules', keywords: ['purchase', 'po'], href: '/erp/purchase' },
    ],
  },
  {
    id: 'online',
    title: 'Online Orders',
    description: 'Marketplace channels, website, QR, WhatsApp and delivery zones.',
    icon: Globe2,
    href: '/erp/online-orders',
    quickActionLabel: 'Open order hub',
    status: 'demo',
    requiredPermission: PERMISSIONS.POS_ACCESS,
    requiredPlanModule: 'pos',
    topics: [
      { id: 'swiggy', label: 'Swiggy', keywords: ['swiggy'], href: '/erp/online-orders', status: 'demo' },
      { id: 'zomato', label: 'Zomato', keywords: ['zomato'], href: '/erp/online-orders', status: 'demo' },
      { id: 'ondc', label: 'ONDC', keywords: ['ondc'], href: '/erp/online-orders', status: 'demo' },
      { id: 'website', label: 'Website', keywords: ['website', 'web'], status: 'planned' },
      { id: 'qr', label: 'QR', keywords: ['qr'], href: '/erp/tables' },
      { id: 'wa', label: 'WhatsApp', keywords: ['whatsapp'], status: 'planned' },
      { id: 'charges', label: 'Delivery Charges', keywords: ['delivery charge'], status: 'planned' },
      { id: 'zones', label: 'Delivery Zones', keywords: ['zone', 'delivery'], status: 'planned' },
      { id: 'routing', label: 'Kitchen Routing', keywords: ['routing'], href: '/erp/kitchen' },
    ],
  },
  {
    id: 'ai',
    title: 'AI Copilot',
    description: 'Enable AI, forecasts, purchase suggestions and insights.',
    icon: Bot,
    href: '/erp/copilot',
    quickActionLabel: 'Open Copilot',
    status: 'live',
    requiredPermission: PERMISSIONS.SAAS_AI,
    requiredPlanModule: 'aiCoach',
    topics: [
      { id: 'enable', label: 'Enable AI', keywords: ['ai', 'copilot'], href: '/erp/copilot' },
      { id: 'perms', label: 'AI Permissions', keywords: ['ai permission'], href: '/erp/settings?tab=permissions' },
      { id: 'forecast', label: 'Sales Forecast', keywords: ['forecast'], href: '/erp/copilot' },
      { id: 'purchase', label: 'Purchase Suggestions', keywords: ['purchase suggestion'], href: '/erp/copilot' },
      { id: 'insights', label: 'Business Insights', keywords: ['insight'], href: '/erp/intelligence' },
      { id: 'recs', label: 'AI Recommendations', keywords: ['recommendation'], href: '/erp/copilot' },
      { id: 'prompts', label: 'Prompt Templates', keywords: ['prompt'], status: 'planned' },
    ],
  },
  {
    id: 'reports',
    title: 'Reports',
    description: 'Dashboards, schedules, auto email, export and KPI configuration.',
    icon: Activity,
    href: '/erp/reports',
    quickActionLabel: 'Open reports',
    status: 'live',
    requiredPermission: PERMISSIONS.REPORTS_VIEW,
    requiredPlanModule: 'reports',
    topics: [
      { id: 'dash', label: 'Dashboard', keywords: ['dashboard', 'report'], href: '/erp/reports' },
      { id: 'schedule', label: 'Report Schedule', keywords: ['schedule'], status: 'planned' },
      { id: 'email', label: 'Auto Email', keywords: ['email report'], status: 'planned' },
      { id: 'export', label: 'Export', keywords: ['export', 'csv'], href: '/erp/reports' },
      { id: 'kpi', label: 'KPI Configuration', keywords: ['kpi'], href: '/erp/intelligence' },
      { id: 'analytics', label: 'Analytics', keywords: ['analytics', 'bi'], href: '/erp/intelligence' },
    ],
  },
  {
    id: 'notifications',
    title: 'Notifications',
    description: 'SMS, WhatsApp, email, push and operational alerts.',
    icon: Bell,
    href: '/erp/audit',
    quickActionLabel: 'Alert center',
    status: 'partial',
    requiredPermission: PERMISSIONS.SETTINGS_MANAGE,
    topics: [
      { id: 'sms', label: 'SMS', keywords: ['sms'], status: 'planned' },
      { id: 'wa', label: 'WhatsApp', keywords: ['whatsapp alert'], status: 'planned' },
      { id: 'email', label: 'Email', keywords: ['email alert'], status: 'planned' },
      { id: 'push', label: 'Push', keywords: ['push'], status: 'partial' },
      { id: 'kitchen', label: 'Kitchen Alerts', keywords: ['kitchen alert'], href: '/erp/kitchen' },
      { id: 'stock', label: 'Low Stock', keywords: ['low stock'], href: '/erp/inventory' },
      { id: 'payment', label: 'Payment Alerts', keywords: ['payment alert'], href: '/erp/refunds' },
      { id: 'printer', label: 'Printer Alerts', keywords: ['printer alert'], href: '/erp/settings' },
    ],
  },
  {
    id: 'hardware',
    title: 'Hardware',
    description: 'Receipt & kitchen printers, scanners, displays and scales.',
    icon: HardDrive,
    href: '/erp/settings',
    quickActionLabel: 'Printer settings',
    status: 'partial',
    requiredPermission: PERMISSIONS.SETTINGS_MANAGE,
    requiredPlanModule: 'settings',
    topics: [
      { id: 'receipt', label: 'Receipt Printer', keywords: ['receipt printer', 'thermal'], href: '/erp/settings' },
      { id: 'kitchen', label: 'Kitchen Printer', keywords: ['kitchen printer'], status: 'planned' },
      { id: 'drawer', label: 'Cash Drawer', keywords: ['cash drawer'], href: '/erp/shifts' },
      { id: 'barcode', label: 'Barcode Scanner', keywords: ['barcode', 'scanner'], status: 'planned' },
      { id: 'qr', label: 'QR Printer', keywords: ['qr printer'], href: '/erp/tables' },
      { id: 'cds', label: 'Customer Display', keywords: ['customer display'], status: 'planned' },
      { id: 'scale', label: 'Weighing Scale', keywords: ['scale', 'weigh'], status: 'planned' },
    ],
  },
  {
    id: 'integrations',
    title: 'Integrations',
    description: 'Accounting, messaging providers, webhooks and API keys.',
    icon: Settings2,
    href: '/erp/api-platform',
    quickActionLabel: 'API & webhooks',
    status: 'partial',
    requiredPermission: PERMISSIONS.SAAS_API,
    requiredPlanModule: 'api',
    topics: [
      { id: 'gmb', label: 'Google Business', keywords: ['google business'], status: 'planned' },
      { id: 'tally', label: 'Tally', keywords: ['tally'], href: '/erp/platform' },
      { id: 'zoho', label: 'Zoho Books', keywords: ['zoho'], status: 'planned' },
      { id: 'qb', label: 'QuickBooks', keywords: ['quickbooks'], status: 'planned' },
      { id: 'xero', label: 'Xero', keywords: ['xero'], status: 'planned' },
      { id: 'wa', label: 'WhatsApp Business', keywords: ['whatsapp business'], status: 'planned' },
      { id: 'sms', label: 'SMS Provider', keywords: ['sms provider'], status: 'planned' },
      { id: 'email', label: 'Email Provider', keywords: ['smtp', 'email provider'], status: 'planned' },
      { id: 'webhook', label: 'Webhook', keywords: ['webhook'], href: '/erp/api-platform' },
      { id: 'keys', label: 'API Keys', keywords: ['api key'], href: '/erp/api-platform' },
    ],
  },
  {
    id: 'branding',
    title: 'Branding',
    description: 'Logo, theme, receipt design, email templates and white label.',
    icon: Paintbrush,
    href: '/erp/settings',
    quickActionLabel: 'Brand & receipts',
    status: 'partial',
    requiredPermission: PERMISSIONS.SETTINGS_MANAGE,
    requiredPlanModule: 'settings',
    topics: [
      { id: 'logo', label: 'Logo', keywords: ['logo', 'brand'], href: '/erp/settings' },
      { id: 'theme', label: 'Theme', keywords: ['theme', 'color'], status: 'planned' },
      { id: 'receipt', label: 'Receipt Design', keywords: ['receipt design'], href: '/erp/settings' },
      { id: 'email', label: 'Email Template', keywords: ['email template'], status: 'planned' },
      { id: 'qr', label: 'QR Branding', keywords: ['qr brand'], href: '/erp/tables' },
      { id: 'wl', label: 'White Label', keywords: ['white label'], status: 'planned' },
      { id: 'domain', label: 'Domain', keywords: ['domain', 'custom domain'], status: 'planned' },
    ],
  },
  {
    id: 'compliance',
    title: 'Compliance',
    description: 'GST invoices, retention, privacy, audit trail and FSSAI.',
    icon: Scale,
    href: '/erp/audit',
    quickActionLabel: 'View audit logs',
    status: 'partial',
    requiredPermission: PERMISSIONS.POS_AUDIT,
    requiredPlanModule: 'pos',
    topics: [
      { id: 'gst', label: 'GST', keywords: ['gst compliance'], href: '/erp/settings' },
      { id: 'invoice', label: 'Invoice Rules', keywords: ['invoice'], href: '/erp/settings' },
      { id: 'retention', label: 'Data Retention', keywords: ['retention', 'gdpr'], status: 'planned' },
      { id: 'privacy', label: 'Privacy', keywords: ['privacy'], status: 'planned' },
      { id: 'terms', label: 'Terms', keywords: ['terms'], status: 'planned' },
      { id: 'audit', label: 'Audit', keywords: ['audit'], href: '/erp/audit' },
      { id: 'fssai', label: 'FSSAI', keywords: ['fssai'], status: 'planned' },
    ],
  },
  {
    id: 'health',
    title: 'System Health',
    description: 'Database, API, realtime, jobs, storage and backups.',
    icon: Activity,
    href: '/erp/platform',
    quickActionLabel: 'Platform health',
    status: 'partial',
    requiredPermission: PERMISSIONS.SAAS_PLATFORM,
    requiredPlanModule: 'centralInventory',
    topics: [
      { id: 'db', label: 'Database', keywords: ['database', 'supabase'], href: '/erp/platform' },
      { id: 'api', label: 'API', keywords: ['api health'], href: '/erp/api-platform' },
      { id: 'rt', label: 'Realtime', keywords: ['realtime'], href: '/erp/platform' },
      { id: 'jobs', label: 'Background Jobs', keywords: ['job', 'queue'], href: '/erp/platform' },
      { id: 'queue', label: 'Queue', keywords: ['queue'], href: '/erp/platform' },
      { id: 'storage', label: 'Storage', keywords: ['storage'], status: 'planned' },
      { id: 'memory', label: 'Memory', keywords: ['memory'], status: 'planned' },
      { id: 'cpu', label: 'CPU', keywords: ['cpu'], status: 'planned' },
      { id: 'logs', label: 'Logs', keywords: ['log'], href: '/erp/audit' },
      { id: 'backups', label: 'Backups', keywords: ['backup'], status: 'planned' },
      { id: 'status', label: 'Health Status', keywords: ['health'], href: '/erp/platform' },
    ],
  },
  {
    id: 'developer',
    title: 'Developer',
    description: 'API keys, feature flags, environment, webhooks and sandbox.',
    icon: Code2,
    href: '/erp/api-platform',
    quickActionLabel: 'Developer console',
    status: 'partial',
    requiredPermission: PERMISSIONS.SAAS_API,
    requiredPlanModule: 'api',
    topics: [
      { id: 'keys', label: 'API Keys', keywords: ['api keys', 'developer'], href: '/erp/api-platform' },
      { id: 'flags', label: 'Feature Flags', keywords: ['feature flag'], href: '/erp/platform' },
      { id: 'env', label: 'Environment', keywords: ['environment', 'prod', 'sandbox'], status: 'planned' },
      { id: 'hooks', label: 'Webhooks', keywords: ['webhook'], href: '/erp/api-platform' },
      { id: 'debug', label: 'Debug Mode', keywords: ['debug'], status: 'planned' },
      { id: 'sandbox', label: 'Sandbox', keywords: ['sandbox'], status: 'planned' },
      { id: 'version', label: 'Version', keywords: ['version', 'release'], status: 'partial' },
    ],
  },
];

export const CONTROL_MODULE_CARDS = CONTROL_MODULES;

export const QUICK_ACTIONS: QuickAction[] = [
  { id: 'outlet', label: 'Create Outlet', href: '/erp/franchise', requiredPermission: PERMISSIONS.FRANCHISE_MANAGE },
  { id: 'user', label: 'Invite User', href: '/erp/users', requiredPermission: PERMISSIONS.USERS_MANAGE },
  { id: 'printer', label: 'Configure Printer', href: '/erp/settings', requiredPermission: PERMISSIONS.SETTINGS_MANAGE },
  { id: 'gateway', label: 'Payment Gateway', href: '/erp/settings?tab=payments', requiredPermission: PERMISSIONS.SETTINGS_MANAGE },
  { id: 'backup', label: 'Backup Database', href: '/erp/platform', requiredPermission: PERMISSIONS.SAAS_PLATFORM },
  { id: 'report', label: 'Generate Report', href: '/erp/reports', requiredPermission: PERMISSIONS.REPORTS_VIEW },
  { id: 'po', label: 'Create Purchase Order', href: '/erp/purchase', requiredPermission: PERMISSIONS.PURCHASE_MANAGE },
  { id: 'audit', label: 'View Audit Logs', href: '/erp/audit', requiredPermission: PERMISSIONS.POS_AUDIT },
];

export function searchControlCatalog(query: string) {
  const q = query.trim().toLowerCase();
  if (!q) return [] as Array<{ moduleId: string; moduleTitle: string; topicLabel: string; href: string; status: string }>;

  const hits: Array<{ moduleId: string; moduleTitle: string; topicLabel: string; href: string; status: string }> = [];

  for (const mod of CONTROL_MODULE_CARDS) {
    const moduleMatch =
      mod.title.toLowerCase().includes(q) ||
      mod.description.toLowerCase().includes(q) ||
      mod.id.includes(q);
    if (moduleMatch) {
      hits.push({
        moduleId: mod.id,
        moduleTitle: mod.title,
        topicLabel: mod.title,
        href: mod.href,
        status: mod.status,
      });
    }
    for (const topic of mod.topics) {
      const topicHit =
        topic.label.toLowerCase().includes(q) ||
        topic.keywords.some((k) => k.toLowerCase().includes(q) || q.includes(k.toLowerCase()));
      if (topicHit) {
        hits.push({
          moduleId: mod.id,
          moduleTitle: mod.title,
          topicLabel: topic.label,
          href: topic.href || mod.href,
          status: topic.status || mod.status,
        });
      }
    }
  }

  // Dedupe by href+label
  const seen = new Set<string>();
  return hits.filter((h) => {
    const key = `${h.href}|${h.topicLabel}`;
    if (seen.has(key)) return false;
    seen.add(key);
    return true;
  }).slice(0, 24);
}
